---
- src: bertvv.samba
- src: cloudalchemy.node-exporter
- src: dev-sec.os-hardening
- src: dev-sec.ssh-hardening
- src: geerlingguy.docker
- src: geerlingguy.firewall
- src: geerlingguy.nfs
- src: geerlingguy.ntp
- src: geerlingguy.pip
- src: geerlingguy.security
- src: geerlingguy.swap
- src: oefenweb.postfix
- src: rvm.ruby
- src: yatesr.timezone

- src: https://github.com/vladgh/ansible-role-common.git
  name: vladgh.common
  version: master
- src: https://github.com/vladgh/ansible-role-hashicorp.git
  name: vladgh.hashicorp
  version: master
- src: https://github.com/vladgh/ansible-role-qemu_guest_agent.git
  name: vladgh.qemu_guest_agent
  version: master
- src: https://github.com/vladgh/ansible-role-shellcheck.git
  name: vladgh.shellcheck
  version: master
