---
- import_playbook: playbooks/ansible.yml
- import_playbook: playbooks/common.yml
- import_playbook: playbooks/sec.yml
- import_playbook: playbooks/vm.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/ruby.yml
- import_playbook: playbooks/monitor.yml
- import_playbook: playbooks/nas.yml
