---
- name: Ansible
  hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
  - name: Update apt-get repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 86400 # Update the apt cache if its older than a day
  - name: Install Python for Ansible
    package:
      name: python3
      state: present
  - name: Ansible user
    user:
      name: ansible
      state: present
      uid: 2674
  - name: Ansible user authorized keys
    authorized_key:
      user: ansible
      key: "{{ deploy_ssh_rsa }}"
      state: present
      exclusive: yes
  - name: Add Ansible user to Sudoers
    lineinfile:
      path: /etc/sudoers.d/00_ansible
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
