---
- name: Common
  hosts: all
  become: yes
  roles:
    - role: vladgh.common
    - role: yatesr.timezone
      when: timezone is defined and timezone
    - role: geerlingguy.swap
      when: swap_file_enabled is defined and swap_file_enabled|bool
