---
# System
timezone: America/Phoenix

# Accounts
accounts:
  - name: vlad
    comment: Vlad Ghinea
    groups: admins
    append: yes
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me
  - name: cosmin
    comment: Cosmin Ionica
    groups: admins
    append: yes
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAN+Ge6UYazTf6rnwdBP7okOdyBNeMUW0pQYkN79ajis cosmin@mec7.com
  - name: cmedia
    comment: Media User
    uid: 7777
