---
# System
timezone: America/Phoenix

# Accounts
local_groups:
  - name: admins
    system: yes
    sudo: yes
local_users:
  - name: vlad
    comment: Vlad Ghinea
    groups: admins
    append: yes
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me
  - name: cosmin
    comment: Cosmin Ionica
    groups: admins
    append: yes
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAN+Ge6UYazTf6rnwdBP7okOdyBNeMUW0pQYkN79ajis cosmin@mec7.com
  - name: cmedia
    shell: /usr/sbin/nologin
    uid: 7777

# Mount points
mount_points:
  - name: UNnas
    path: /data/MEDIA
    src: 192.168.7.10:/HOME/media
    opts: soft
    fstype: nfs
    owner: cmedia
    group: cmedia

# Cron Jobs
cron_jobs:
  - name: Docker Maintenance
    minute: '3'
    hour: '3'
    weekday: '0'
    job: ( cd /opt/seed; /usr/bin/docker-compose pull; /usr/bin/docker-compose up --detach --remove-orphans --force-recreate; docker system prune --all --force ) 2>&1 | /usr/bin/logger -t DockerMaintenance

# Additional packages
additional_packages:
  - intel-media-va-driver-non-free
  - i965-va-driver
  - libmfx1

# EMail
postfix_relayhost: smtp.sendgrid.net
postfix_relayhost_port: 587
postfix_relaytls: true
postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
postfix_sasl_user: apikey
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"
postfix_aliases:
  - user: root
    alias: cosmin@mec7.com
postfix_header_checks:
  - pattern: '/From:.*/'
    action: 'REPLACE'
    text: 'From: Cosmin <cosmin@mec7.com>'
