---
# NFS Server
nfs_exports:
  - '/data *(rw,sync,all_squash,anonuid=7777,anongid=7777)'

# Samba Server
samba_netbios_name: NAS
samba_server_string: 'NAS'
samba_workgroup: WORKGROUP
samba_load_printers: 'no'
samba_mitigate_cve_2017_7494: 'no'
samba_users: "{{ vault_samba_users }}"
samba_shares:
  - name: backup
    comment: 'Backup'
    path: '/data/backup'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'cmedia'
    owner: 'cmedia'
    group: 'cmedia'
    create_mode: '0664'
    force_create_mode: '0664'
    directory_mode: '0775'
    force_directory_mode: '0775'
  - name: home
    comment: 'Home'
    path: '/data/home'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'cmedia'
    owner: 'cmedia'
    group: 'cmedia'
    create_mode: '0664'
    force_create_mode: '0664'
    directory_mode: '0775'
    force_directory_mode: '0775'
  - name: work
    comment: 'Work'
    path: '/data/work'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'cmedia'
    owner: 'cmedia'
    group: 'cmedia'
    create_mode: '0664'
    force_create_mode: '0664'
    directory_mode: '0775'
    force_directory_mode: '0775'
  - name: media
    comment: 'Media'
    path: '/data/MEDIA'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'cmedia cosmin'
    owner: 'cmedia'
    group: 'cmedia'
    create_mode: '0664'
    force_create_mode: '0664'
    directory_mode: '0775'
    force_directory_mode: '0775'
