---
- name: Debug
  hosts: all
  vars:
    show_facts: no
    debugging: yes
  tasks:
    - name: Show Ansible Facts
      debug:
        var: ansible_facts
      when: show_facts is defined and show_facts|bool
    - name: Debug
      debug:
        msg: Debugged
      when: debugging is defined and debugging|bool
