---
- name: Docker hosts
  hosts: docker
  become: yes
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_install_compose: yes
    docker_compose_version: '1.25.0'
  roles:
    - geerlingguy.docker
  post_tasks:
    - name: Run a daily docker clean-up
      cron:
        name: Docker CleanUp
        minute: '2'
        hour: '2'
        job: docker system prune --force 2>&1 | /usr/bin/logger -t DockerCleanUp
