---
- name: Proxmox Virtual Environment
  hosts: proxmox
  become: yes
  tasks:
    - name: Remove automatically installed PVE Enterprise repo configuration
      apt_repository:
        repo: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
        filename: pve-enterprise
        state: absent
      register: _pve_enterprise_repo
    - name: Add community repo configuration
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        filename: pve-no-subscription
        state: present
      register: _pve_no_subscription_repo
    - name: Update Apt cache on repository changes
      apt:
        update_cache: yes
        force_apt_get: yes
      when: _pve_enterprise_repo is changed or _pve_no_subscription_repo is changed
      register: _pve_update_apt_cache
      until: _pve_update_apt_cache is success
      retries: 3
      delay: 2
  #   - name: Configure email address for ZFS event daemon notifications
  #     lineinfile:
  #       dest: /etc/zfs/zed.d/zed.rc
  #       line: 'ZED_EMAIL_ADDR="{{ pve_zfs_zed_email }}"'
  #       regexp: '^#?ZED_EMAIL_ADDR='
  #     notify:
  #       - Restart zfs-zed
  #     when: pve_zfs_zed_email is defined and pve_zfs_zed_email
  # handlers:
  #   - name: Restart zfs-zed
  #     service:
  #       name: zfs-zed
  #       state: restarted
