---
# Security-related configurations, compliant with the DevSec Linux Baseline (https://github.com/dev-sec/linux-baseline).
- name: Bastion host hardening
  hosts: bastion
  become: yes
  roles:
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - geerlingguy.security
