---
- name: Virtual Machine
  hosts: virtual
  become: yes
  roles:
    - vladgh.qemu_guest_agent
  tasks:
    # The timesyncd service provided by systemd conflicts with the ntp service (which we need for timezone) on Ubuntu 18 VMs
    - name: Disable systemd-timesyncd.service - Network Time Synchronization
      systemd:
        name: systemd-timesyncd
        state: stopped
        enabled: no
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18'
    # Fix for "A start job is running for wait for network to be configured" 2 minute delay on Ubuntu 18 VMs
    - name: Disable and mask systemd-networkd-wait-online
      systemd:
        name: systemd-networkd-wait-online
        state: stopped
        enabled: no
        masked: yes
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18'
