---
# Logs
install_ca_certificates: 'yes'
remote_logs_enabled: 'yes'
remote_logs_server: 'listener.logz.io'
remote_logs_port: '5001'
remote_logs_permitted_peer: '*.logz.io'
remote_logs_template:
  name: 'logzFormatFileTagName'
  string: '[{{ vault_logzio_token }}] <%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [type=syslog] %msg%\n'
