name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '46 */6 * * *'

jobs:
  build:
    env:
      VAULT_VERSION: '1.3.1'
      VAULT_ADDR: 'https://vault.ghn.me:8200'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install --upgrade pip ansible hvac pycrypto paramiko
    - name: Install Vault
      run: |
            wget -q "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
            wget -qO - "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS" | grep linux_amd64 | sha256sum -c
            sudo unzip -d /usr/local/bin/ "vault_${VAULT_VERSION}_linux_amd64.zip"
            vault version
    - name: Authenticate Vault
      run: |
            VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=${{ secrets.VAULT_ROLE_ID }} secret_id=${{ secrets.VAULT_SECRET_ID }})
            echo ::add-mask::$VAULT_TOKEN
            echo ::set-env name=VAULT_TOKEN::$VAULT_TOKEN
    - name: Get secrets from Vault
      run: vault kv get -field=id_rsa mec7/deploy > deploy_rsa && chmod 600 deploy_rsa
    - name: Download Ansible roles
      run: ansible-galaxy install --role-file requirements.yml
    - name: Run Ansible
      run: ansible-playbook site.yml
